[project]
name = "llamaindex-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.8",
    "crawl4ai>=0.8.6",
    "dotenv-python>=0.0.1",
    "google-genai>=1.73.1",
    "llama-index>=0.14.16",
    "llama-index-core>=0.14.20",
    "llama-index-embeddings-huggingface>=0.7.0",
    "llama-index-llms-gemini>=0.6.2",
    "llama-index-llms-google-genai>=0.9.1",
    "llama-index-llms-groq>=0.5.0",
    "llama-index-readers-web>=0.6.0",
    "llama-index-vector-stores-chroma>=0.5.5",
    "llama-index-vector-stores-pinecone>=0.8.0",
    "pinecone-client>=6.0.0",
    "python-dotenv>=1.2.2",
    "streamlit>=1.57.0",
]
